### PR TITLE
Fix "Publish Draft" Bug

### LINKED ISSUE #411: 🐞🚨 "Publish Draft" Button Not Working
#### Description

We're getting a lot of people reporting that they are unable to publish their draft because the publish button doesn't do anything. Haven't had a chance to diagnose the issue yet so will update this as soon as I can

#### Repro Steps

1. Create a draft
2. Try to publish it

### PR DESCRIPTION
**Pull request by robin-macpherson**
## Description

**Issue:** closes #411 

User's aren't unable to publish their drafts.
This was due to looking for `args.languageId` instead of `originalPost.languageId` since languageId is not required in the `updatePost` mutation.

## Subtasks

- [x] I have added this PR to the Journaly Kanban project ✅
- [x] Find the issue
- [x] Make the fix

## Migrations

No migs.

### CODE REVIEW

File: nexus/post.ts [hunk 1]
```diff
@@ -518,7 +518,7 @@ const PostMutations = extendType({
           }))
         }
 
-        const userLanguageLevel = currentUser.languages.filter((language: LanguageRelation) => language.languageId === args.languageId)[0].level
+        const userLanguageLevel = currentUser.languages.filter((language: LanguageRelation) => language.languageId === originalPost.languageId)[0].level
```
Comment (Lanny) [inline nexus/post.ts:521]:
```suggestion
        const languageId = args.languageId  || originalPost.languageId
        const userLanguageLevel = currentUser.languages.filter((language: LanguageRelation) => language.languageId ===languageId)[0].level
```

**Review by Lanny — APPROVED** [review]
